# Generated by Django 2.2.7 on 2019-11-30 21:03

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=60)),
                ('redirect_url', models.CharField(blank=True, max_length=60)),
                ('disqualification_url', models.CharField(blank=True, max_length=60)),
                ('response_count', models.IntegerField(blank=True)),
                ('closed_page_message', models.CharField(blank=True, max_length=60)),
                ('href', models.CharField(blank=True, max_length=60)),
                ('close_date', models.DateTimeField(blank=True)),
                ('display_survey_results', models.BooleanField()),
                ('open', models.BooleanField()),
                ('disqualification_type', models.CharField(blank=True, max_length=60)),
                ('allow_multiple_responses', models.BooleanField()),
                ('anonymous_type', models.CharField(blank=True, max_length=60)),
                ('name', models.CharField(blank=True, max_length=60)),
                ('survey_id', models.CharField(blank=True, max_length=60)),
                ('password_enabled', models.BooleanField()),
                ('date_modified', models.DateTimeField(blank=True)),
                ('url', models.CharField(blank=True, max_length=60)),
                ('edit_response_type', models.CharField(blank=True, max_length=60)),
                ('redirect_type', models.CharField(blank=True, max_length=60)),
                ('sender_email', models.CharField(blank=True, max_length=60)),
                ('thank_you_message', models.CharField(blank=True, max_length=60)),
                ('date_created', models.DateTimeField(blank=True)),
                ('disqualification_message', models.CharField(blank=True, max_length=60)),
                ('type', models.CharField(blank=True, max_length=60)),
                ('response_limit', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='nombre del estudio', max_length=30)),
                ('token', models.CharField(help_text='API SurveyMonkey Token', max_length=120)),
                ('survey', models.CharField(help_text='ID SurveyMonkey', max_length=120)),
                ('message_remainder', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('message_sentHour', models.IntegerField()),
                ('default_collector', models.CharField(help_text='Colector inicial', max_length=32)),
                ('get_response_startOf', models.CharField(max_length=32)),
                ('get_response_endOf', models.CharField(max_length=32)),
                ('get_response_type', models.CharField(choices=[('days', 'DIA'), ('hours', 'HORA'), ('weeks', 'SEMANA'), ('minutes', 'MINUTO'), ('months', 'MES')], max_length=15)),
                ('comprehend_atribute', models.CharField(max_length=32)),
                ('comprehend_questions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), size=None)),
                ('comprehend_textByResponse', models.IntegerField()),
                ('email_Source', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('responded', 'Respuesta de Agradecimiento'), ('notification', 'Notificacion')], max_length=15)),
                ('TemplateName', models.CharField(max_length=32)),
                ('SubjectPart', models.CharField(max_length=32)),
                ('HtmlPart', models.CharField(max_length=1020)),
                ('TextPart', models.CharField(max_length=1020)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('invite', 'INVITACION'), ('reminder', 'RECORDATOPRIO'), ('thank_you', 'AGRADECIMIENTO')], max_length=15)),
                ('recipient_status', models.CharField(choices=[('has_not_responded', 'SIN RESPONDER'), ('partially_responded', 'CON RESPUESTAS PARCIALES'), ('completed', 'ENCUESTA COMPLETA'), ('responded', 'RESPONDIO')], max_length=15)),
                ('subject', models.CharField(max_length=60)),
                ('body_html', models.CharField(max_length=1020)),
                ('embed_first_question', models.BooleanField()),
                ('is_branding_enabled', models.BooleanField()),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudio_messages', to='estudios.Estudio')),
            ],
        ),
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudio_blacklist', to='estudios.Estudio')),
            ],
        ),
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), size=None)),
                ('name', models.CharField(max_length=32)),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudio_alerts', to='estudios.Estudio')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_alerts', to='estudios.Template')),
            ],
        ),
    ]
