# Generated by Django 2.2.7 on 2019-12-13 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hermandad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido_paterno', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('genero', models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMENINO')], max_length=1)),
                ('hermanos', models.ManyToManyField(related_name='mis_hermanos', through='personas.Hermandad', to='personas.Persona')),
                ('madre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos_de_la_madre', to='personas.Persona')),
                ('padre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos_del_padre', to='personas.Persona')),
                ('pareja', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mi_pareja', to='personas.Persona')),
            ],
        ),
        migrations.AddField(
            model_name='hermandad',
            name='persona_dos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_to_set', to='personas.Persona'),
        ),
        migrations.AddField(
            model_name='hermandad',
            name='persona_uno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_from_set', to='personas.Persona'),
        ),
    ]
