# Generated by Django 2.2.7 on 2019-11-23 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='hermanos',
        ),
    ]
